- name: Copy exit_trust_root binary
  copy:
    src: "{{playbook_dir}}/exit_trust_root_server"
    dest: /usr/bin/exit_trust_root_server
    mode: 0755
  become: true

- name: Template Exit Trust Root service file
  template:
    src: exit-trust-root.service.j2
    dest: /etc/systemd/system/exit-trust-root.service
  become: true

- name: Set Exit Trust Root to run on startup
  systemd:
    daemon_reload: true
    name: exit-trust-root
    state: restarted
    enabled: true
  become: true

- name: Wait for Quick crashes
  pause:
    seconds: 5

- name: Check if Exit Trust Root is running
  command: systemctl status exit-trust-root
  ignore_errors: true
  changed_when: false
  register: service_exit_trust_root_status

- name: Report status of Exit Trust Root
  fail:
    msg: |
      Service exit-trust-root is not running.
      Output of `systemctl status exit-trust-root`:
      {{ service_exit_trust_root_status.stdout }}
      {{ service_exit_trust_root_status.stderr }}
  when: service_exit_trust_root_status is failed