name: Deploy

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  ANSIBLE_HOST_KEY_CHECKING: False
  SSH_KEY: ${{ secrets.SSH_KEY }}

jobs:
  deploy:
    name: Build and Deploy Exit Root of Trust
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: "backend/"
          cache-on-failure: true
          cache-all-crates: true
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install Python dependencies.
        run: pip3 install ansible github3.py certbot certbot-dns-cloudflare
      - name: Install cross
        run: cargo install cross
      - name: Setup SSH Connectivity
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
      - name: Build and deploy Exit Root of Trust
        run: bash scripts/build-and-deploy.sh
